version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ao-cu-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '21726:5432'
